spring:
  application:
    name: Swagger demo project
  datasource:
    initialization-mode: always
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: ALWAYS #разноцветные буковки в консоли

springdoc:
  swagger-ui:
    operationsSorter: method  #сортировка вывода методов контроллера
